# Generated by Django 5.2.8 on 2026-06-10 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyseSymptome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte_symptomes', models.TextField()),
                ('score_confiance', models.FloatField(default=0.0)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.profilpatient')),
                ('specialite_recommandee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctors.specialite')),
            ],
        ),
    ]
