# Generated by Django 5.2.8 on 2026-06-10 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone_professionnel', models.CharField(max_length=20)),
                ('adresse_cabinet', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('annees_experience', models.PositiveSmallIntegerField(default=0)),
                ('statut_actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='doctors/photos/')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medecin_profile', to=settings.AUTH_USER_MODEL)),
                ('specialite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medecins', to='doctors.specialite')),
            ],
        ),
    ]
