# Generated by Django 5.2.8 on 2026-06-10 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disponibilite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('est_reserve', models.BooleanField(default=False)),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilites', to='doctors.medecin')),
            ],
            options={
                'ordering': ['date', 'heure_debut'],
                'constraints': [models.UniqueConstraint(fields=('medecin', 'date', 'heure_debut'), name='unique_disponibilite_medecin_creneau')],
            },
        ),
    ]
