# Generated by Django 5.2.8 on 2026-06-10 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
                ('motif', models.TextField()),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('confirme', 'Confirmé'), ('annule', 'Annulé'), ('termine', 'Terminé'), ('absent', 'Absent')], default='en_attente', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous', to='doctors.medecin')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous', to='patients.profilpatient')),
                ('specialite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous', to='doctors.specialite')),
            ],
            options={
                'ordering': ['date', 'heure'],
                'constraints': [models.UniqueConstraint(fields=('medecin', 'date', 'heure'), name='unique_rendezvous_medecin_creneau')],
            },
        ),
    ]
